### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file()

### ISSUE THREAD

**Issue by cbtsgithub** [nioc/linky-collector#1]
Hello,
When i try the php script, i obtain an error:

```
root@metrix02:/opt/linky-collector# php -f /opt/linky-collector/index.php

PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_file() in /opt/linky-collector/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterXML.php:87
Stack trace:
#0 /opt/linky-collector/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterXML.php(42): LoggerConfigurationAdapterXML->loadXML('config.xml')
#1 /opt/linky-collector/vendor/apache/log4php/src/main/php/configurators/LoggerConfiguratorDefault.php(158): LoggerConfigurationAdapterXML->convert('config.xml')
#2 /opt/linky-collector/vendor/apache/log4php/src/main/php/configurators/LoggerConfiguratorDefault.php(114): LoggerConfiguratorDefault->parseFile('config.xml')
#3 /opt/linky-collector/vendor/apache/log4php/src/main/php/configurators/LoggerConfiguratorDefault.php(83): LoggerConfiguratorDefault->parse('config.xml')
#4 /opt/linky-collector/vendor/apache/log4php/src/main/php/Logger.php(543): LoggerConfiguratorDefault->configure(Object(LoggerHierarchy), 'config.xml')
#5 /opt/linky-collector/index.php(10): Log in /opt/linky-collector/vendor/apache/log4php/src/main/php/configurators/LoggerConfigurationAdapterXML.php on line 87
```

Could you please help me ?
Thanks.
Chris

**Comment by cbtsgithub** [comment]
Arghhhh found that i needed to install php-xml and php-curl to avoid the error !!

**Comment by nioc** [comment]
Correct 👍
Unfortunately, this script does not work anymore since Enedis has changed authentication mechanism without providing public API…
